### ISSUE TITLE
Tag Creation Bug

### ISSUE THREAD

**Issue by YeezyMcFeezy** [top-gg/issues#749]
#### Expected Behavior

I expected to be able to create my own tags for my bots top.gg page

#### Observed Behavior

Instead, I found an issue where I couldn't create tags and it would make a small empty bubble

#### Applicable Links or Attachments

[GIF of the issue: https://gyazo.com/92ef30163489ed9c5eb2af72638a9daa ]

#### Steps to Reproduce

1. Open top.gg
2. Go to your bot page
3. Press edit
4. Go to "Tags" and type a tag with no results (Custom Tag)
5. Press "Create Tag" or ENTER key 

#### Web Browser and Version

Google Chrome 91.0.4472.124 (Official Build) (64-bit) (cohort: stable_gradual_rollout)

#### Operating System and Version

Windows 10 OS Version 2004 (Build 19041.1083)

#### Screen Resolution

1920 x 1080

#### Additional Information/Comments

It is slightly annoying as it doesn't allow you to make tags that greatly describe your bot

**Comment by YeezyMcFeezy** [comment]
Any updates?

**Comment by velddev** [comment]
Sadly, not yet. I've been looking into it, but not sure yet.

**Comment by YeezyMcFeezy** [comment]
All good, I just wanted to see if someone might've found the issue

**Comment by aziznatour** [comment]
Can confirm issue occurs in Firefox 91.0
![GIF 10-08-2021 10-41-28](https://user-images.githubusercontent.com/8480865/129197126-65af2bd4-d6c9-4232-a98e-b5af71e5d655.gif)
Would appreciate fixing this for SEO improvement
Thank you

**Comment by IacovlevMaxim** [comment]
Managed to recreate this issue in Google Chrome 92.0.4515.131. Tried "translate" tag aswell.
<img width="1439" alt="Screenshot 2021-08-12 at 15 35 49" src="https://user-images.githubusercontent.com/37591746/129197725-82407491-2618-4f66-bc5e-18e6989b2af8.png">

**Comment by YeezyMcFeezy** [comment]
Any updates so far?

**Comment by SugarCrush1** [comment]
No because the staff don’t do anything and it’s a broken website

**Comment by Creeper55k** [comment]
> No because the staff don’t do anything and it’s a broken website - who has 264 issues on their website opened

Maybe it’s because the devs are humans. Remember the original website developer is not here to maintain it 24/7. There’s only a handful of people who can maintain the server. There’s also a few less people who can maintain the website itself. No offense to the top.gg staff.

**Comment by SugarCrush1** [comment]
Humans, or lazy ones? Issues are open for over a year and they are just targeted on revenue “More ads” “Premium” “Auctions” etc. when is there going to be an announcement like “Fixing issues?” It’s getting annoying and hindering basic abilities now and it’s quite frankly annoying.

**Comment by Creeper55k** [comment]
> Humans, or lazy ones? Issues are open for over a year and they are just targeted on revenue “More ads” “Premium” “Auctions” etc. when is there going to be an announcement like “Fixing issues?” It’s getting annoying and hindering basic abilities now and it’s quite frankly annoying.

Sounds like most businesses ngl

**Comment by SugarCrush1** [comment]
Sounds like money hungry people ngl

**Comment by ExtremeDevelopments** [comment]
We have not announced anything about Auctions, more ads, or premium anywhere?

**Comment by SugarCrush1** [comment]
When will they fix the issues. Tbh the issues will be fixed when the earth ends

**Comment by ExtremeDevelopments** [comment]
There is no ETA on any issues. Just like if you were trying to fix a issue on your bot it can take 30 seconds or longer depending on what it is

**Comment by ExtremeDevelopments** [comment]
The entire code-base underwent a rewrite and the issues are slowly being worked on despite what you see at the moment with this single one.

**Comment by ExtremeDevelopments** [comment]
Once the team doesn't have to maintain 3 code-bases and we are down to only 1 then a lot of these issues will be fixed.

**Comment by SugarCrush1** [comment]
Let’s hope so

**Comment by SugarCrush1** [comment]
Also nice staff team experiences https://medium.com/@discordreplier/top-gg-staff-experience-16673288e5db

**Comment by SugarCrush1** [comment]
^ it’s true

**Comment by velddev** [comment]
Oh, this issue has been fixed. :)

**Comment by YeezyMcFeezy** [comment]
This I believe is partially fixed, upon typing a tag with a capital letter to start (Aussie) it will be made as (aussie) in lowercase 
![image](https://user-images.githubusercontent.com/78299278/134623887-31bb5c44-0cf8-4e2e-b682-031f41a758bf.png)

**Comment by ExtremeDevelopments** [comment]
Iirc it's meant to be like that so there isn't a `Aussie` and `aussie` tag for example

**Comment by velddev** [comment]
Yes, we have a display name, we can change them in the near future, but for now we assume the correct capitalization is based on the original creator of the tag.
